/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


#ifndef _Included_vn_tek4tv_radioip_ui_SerialPort
#define _Included_vn_tek4tv_radioip_ui_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_vn_tek4tv_radioip_ui_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vn_tek4tv_radioip_ui_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
